#!/bin/bash
#==============================================================================
# eza Installer
#
# A modern replacement for ls
# https://github.com/eza-community/eza
#
# Installs via Homebrew for latest version
#
# Usage: ./eza.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# shellcheck source=scripts/lib/core.sh
source "${SCRIPT_DIR}/../lib/core.sh"
# shellcheck source=scripts/lib/health.sh
source "${SCRIPT_DIR}/../lib/health.sh"
# shellcheck source=scripts/lib/dryrun.sh
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="eza"
BREW_PREFIX="/home/linuxbrew/.linuxbrew"

# Add brew to PATH for detection
[[ -x "${BREW_PREFIX}/bin/brew" ]] && eval "$("${BREW_PREFIX}/bin/brew" shellenv)"

is_installed() { command_exists eza; }

get_installed_version() {
    if is_installed; then
        eza --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

do_install() {
    log_info "Installing eza via Homebrew..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: brew install eza"
        return 0
    fi

    if ! command_exists brew; then
        log_error "Homebrew not installed. Please install homebrew first."
        return 1
    fi

    brew install eza

    log_success "eza installed"
}

verify() {
    if ! is_installed; then
        health_fail "${PACKAGE_NAME}" "not installed"
        return 1
    fi
    health_pass "${PACKAGE_NAME}" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/35-eza.sh"
    mkdir -p "$(dirname "${config_file}")" 2>/dev/null || true

    # shellcheck disable=SC2016
    write_or_print "${config_file}" '# eza - modern replacement for ls
# Generated by eza.sh

if command -v eza &> /dev/null; then
    alias ls="eza --icons --git"
    alias ll="eza -l --icons --git"
    alias lt="eza -l --icons --git -T --level=2"
    alias la="eza -la --icons --git"
fi
'
}

main() {
    parse_dry_run_flag "$@"

    # Extract action from args, skipping flags
    local action="install"
    for arg in "$@"; do
        case "${arg}" in
            --dry-run|-n) ;;  # Skip flags
            *) action="${arg}"; break ;;
        esac
    done

    # shellcheck source=config.env.template
    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_EZA_ENABLED:-true}" != "true" ]] && { log_info "eza disabled"; return 0; }

    case "${action}" in
        install|update)
            if is_installed && [[ "${action}" == "install" ]]; then
                log_success "eza already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version)
            if is_installed; then
                get_installed_version
            else
                echo "not installed"
                return 1
            fi
            ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
