#!/bin/bash
#==============================================================================
# FZF Installer
#
# A command-line fuzzy finder
# https://github.com/junegunn/fzf
#
# Installs via apt and configures zsh integration
#
# Usage: ./fzf.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# shellcheck source=scripts/lib/core.sh
source "${SCRIPT_DIR}/../lib/core.sh"
# shellcheck source=scripts/lib/health.sh
source "${SCRIPT_DIR}/../lib/health.sh"
# shellcheck source=scripts/lib/dryrun.sh
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="fzf"

is_installed() { command_exists fzf; }

get_installed_version() {
    if is_installed; then
        fzf --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

do_install() {
    log_info "Installing fzf via apt..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: apt-get install -y fzf"
        return 0
    fi

    apt_or_print install -y -qq fzf

    log_success "fzf installed"
}

verify() {
    if ! is_installed; then
        health_fail "${PACKAGE_NAME}" "not installed"
        return 1
    fi
    health_pass "${PACKAGE_NAME}" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/80-fzf.sh"
    mkdir -p "$(dirname "${config_file}")" 2>/dev/null || true

    # shellcheck disable=SC2016
    write_or_print "${config_file}" '# FZF - command-line fuzzy finder
# Generated by fzf.sh

if command -v fzf &> /dev/null; then
    # Use fd if available for better performance
    if command -v fd &> /dev/null; then
        export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"
        export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
        export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"
    fi

    # Use rg if available and fd is not
    if ! command -v fd &> /dev/null && command -v rg &> /dev/null; then
        export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob \"!.git\""
        export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    fi

    # FZF options
    export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"

    # Set up fzf key bindings and fuzzy completion for zsh
    source <(fzf --zsh 2>/dev/null) || {
        # Fallback for older fzf versions
        [[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]] && source /usr/share/doc/fzf/examples/key-bindings.zsh
        [[ -f /usr/share/doc/fzf/examples/completion.zsh ]] && source /usr/share/doc/fzf/examples/completion.zsh
    }
fi
'
}

main() {
    parse_dry_run_flag "$@"

    # Extract action from args, skipping flags
    local action="install"
    for arg in "$@"; do
        case "${arg}" in
            --dry-run|-n) ;;  # Skip flags
            *) action="${arg}"; break ;;
        esac
    done

    # shellcheck source=config.env.template
    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_FZF_ENABLED:-true}" != "true" ]] && { log_info "fzf disabled"; return 0; }

    case "${action}" in
        install|update)
            if is_installed && [[ "${action}" == "install" ]]; then
                log_success "fzf already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version)
            if is_installed; then
                get_installed_version
            else
                echo "not installed"
                return 1
            fi
            ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
