#!/bin/bash
#==============================================================================
# GitHub CLI (gh) Installer
#
# GitHub's official command line tool
# https://github.com/cli/cli
#
# Installs via Homebrew for latest version
#
# Usage: ./github-cli.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# shellcheck source=scripts/lib/core.sh
source "${SCRIPT_DIR}/../lib/core.sh"
# shellcheck source=scripts/lib/health.sh
source "${SCRIPT_DIR}/../lib/health.sh"
# shellcheck source=scripts/lib/dryrun.sh
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="gh"

# shellcheck source=scripts/lib/brew.sh
source "${SCRIPT_DIR}/../lib/brew.sh"

is_installed() { command_exists gh; }

get_installed_version() {
    if is_installed; then
        gh --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

do_install() {
    log_info "Installing GitHub CLI via Homebrew..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: brew install gh"
        return 0
    fi

    if ! command_exists brew; then
        log_error "Homebrew not installed. Please install homebrew first."
        return 1
    fi

    brew install gh

    log_success "GitHub CLI installed"
}

do_update() {
    log_info "Updating GitHub CLI via Homebrew..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: brew upgrade gh"
        return 0
    fi

    if ! command_exists brew; then
        log_error "Homebrew not installed. Please install homebrew first."
        return 1
    fi

    brew upgrade gh || {
        # brew upgrade fails if already up-to-date, which is fine
        log_info "GitHub CLI is already up-to-date"
    }

    log_success "GitHub CLI updated"
}

verify() {
    if ! is_installed; then
        health_fail "${PACKAGE_NAME}" "not installed"
        return 1
    fi
    health_pass "${PACKAGE_NAME}" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/38-github-cli.sh"
    mkdir -p "$(dirname "${config_file}")" 2>/dev/null || true
    write_or_print "${config_file}" '# GitHub CLI configuration
# Generated by github-cli.sh

# gh aliases
alias ghpr="gh pr"
alias ghprc="gh pr create"
alias ghprv="gh pr view"
alias ghprl="gh pr list"
alias ghi="gh issue"
alias ghic="gh issue create"
alias ghiv="gh issue view"
alias ghil="gh issue list"
'
}

main() {
    parse_dry_run_flag "$@"

    # Extract action from args, skipping flags
    local action="install"
    for arg in "$@"; do
        case "${arg}" in
            --dry-run|-n) ;;  # Skip flags
            *) action="${arg}"; break ;;
        esac
    done

    # shellcheck source=config.env.template
    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_GITHUB_CLI_ENABLED:-true}" != "true" ]] && { log_info "GitHub CLI disabled"; return 0; }

    case "${action}" in
        install)
            if is_installed; then
                log_success "GitHub CLI already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        update)
            if is_installed; then
                do_update
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version)
            if is_installed; then
                get_installed_version
            else
                echo "not installed"
                return 1
            fi
            ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
