#!/bin/bash
#==============================================================================
# Homebrew Installer
#
# The Missing Package Manager for macOS (or Linux)
# https://brew.sh / https://docs.brew.sh/Homebrew-on-Linux
#
# Installs Homebrew to /home/linuxbrew/.linuxbrew
#
# Usage: ./homebrew.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# shellcheck source=scripts/lib/core.sh
source "${SCRIPT_DIR}/../lib/core.sh"
# shellcheck source=scripts/lib/health.sh
source "${SCRIPT_DIR}/../lib/health.sh"
# shellcheck source=scripts/lib/dryrun.sh
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="homebrew"
BREW_PREFIX="/home/linuxbrew/.linuxbrew"

# Add brew to PATH for detection
[[ -x "${BREW_PREFIX}/bin/brew" ]] && eval "$("${BREW_PREFIX}/bin/brew" shellenv)"

is_installed() {
    command_exists brew
}

get_installed_version() {
    if is_installed; then
        brew --version 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

do_install() {
    log_info "Installing Homebrew..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
        return 0
    fi

    # Install Homebrew non-interactively
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    # Source brew shellenv for immediate use
    if [[ -x "${BREW_PREFIX}/bin/brew" ]]; then
        eval "$("${BREW_PREFIX}/bin/brew" shellenv)"
    fi

    log_success "Homebrew installed"
}

do_update() {
    log_info "Updating Homebrew..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: brew update"
        return 0
    fi

    brew update

    log_success "Homebrew updated"
}

verify() {
    if ! is_installed; then
        health_fail "${PACKAGE_NAME}" "not installed"
        return 1
    fi
    health_pass "${PACKAGE_NAME}" "v$(get_installed_version)"

    # Run brew doctor for additional checks
    if is_installed && ! is_dry_run; then
        if brew doctor &>/dev/null; then
            health_pass "brew doctor" "no issues"
        else
            health_warn "brew doctor" "has warnings (run 'brew doctor' for details)"
        fi
    fi

    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/30-homebrew.sh"
    mkdir -p "$(dirname "${config_file}")" 2>/dev/null || true

    # shellcheck disable=SC2016
    write_or_print "${config_file}" '# Homebrew package manager
# Generated by homebrew.sh

# Initialize Homebrew environment
if [[ -x "/home/linuxbrew/.linuxbrew/bin/brew" ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
'
}

main() {
    parse_dry_run_flag "$@"

    # Extract action from args, skipping flags
    local action="install"
    for arg in "$@"; do
        case "${arg}" in
            --dry-run|-n) ;;  # Skip flags
            *) action="${arg}"; break ;;
        esac
    done

    # shellcheck source=config.env.template
    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_HOMEBREW_ENABLED:-true}" != "true" ]] && { log_info "homebrew disabled"; return 0; }

    case "${action}" in
        install)
            if is_installed; then
                log_success "Homebrew already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        update)
            if is_installed; then
                do_update
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version)
            if is_installed; then
                get_installed_version
            else
                echo "not installed"
                return 1
            fi
            ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
