#!/bin/bash
#==============================================================================
# Neovim Installer
#
# Hyperextensible Vim-based text editor
# https://neovim.io
#
# Installs via Homebrew for latest version
#
# Usage: ./neovim.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# shellcheck source=scripts/lib/core.sh
source "${SCRIPT_DIR}/../lib/core.sh"
# shellcheck source=scripts/lib/health.sh
source "${SCRIPT_DIR}/../lib/health.sh"
# shellcheck source=scripts/lib/dryrun.sh
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="neovim"

# shellcheck source=scripts/lib/brew.sh
source "${SCRIPT_DIR}/../lib/brew.sh"

is_installed() { command_exists nvim; }

get_installed_version() {
    if is_installed; then
        nvim --version 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

do_install() {
    log_info "Installing neovim via Homebrew..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: brew install neovim"
        return 0
    fi

    if ! command_exists brew; then
        log_error "Homebrew not installed. Please install homebrew first."
        return 1
    fi

    brew install neovim

    log_success "neovim installed"
}

do_update() {
    log_info "Updating neovim via Homebrew..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: brew upgrade neovim"
        return 0
    fi

    if ! command_exists brew; then
        log_error "Homebrew not installed. Please install homebrew first."
        return 1
    fi

    brew upgrade neovim || {
        log_info "neovim is already up-to-date"
    }

    log_success "neovim updated"
}

verify() {
    if ! is_installed; then
        health_fail "${PACKAGE_NAME}" "not installed"
        return 1
    fi
    health_pass "${PACKAGE_NAME}" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/50-neovim.sh"
    mkdir -p "$(dirname "${config_file}")" 2>/dev/null || true

    # shellcheck disable=SC2016
    write_or_print "${config_file}" '# Neovim - Hyperextensible Vim-based text editor
# Generated by neovim.sh

if command -v nvim &> /dev/null; then
    export EDITOR="nvim"
    export VISUAL="nvim"
    alias vim="nvim"
    alias vi="nvim"
fi
'
}

main() {
    parse_dry_run_flag "$@"

    # Extract action from args, skipping flags
    local action="install"
    for arg in "$@"; do
        case "${arg}" in
            --dry-run|-n) ;;  # Skip flags
            *) action="${arg}"; break ;;
        esac
    done

    # shellcheck source=config.env.template
    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_NEOVIM_ENABLED:-true}" != "true" ]] && { log_info "neovim disabled"; return 0; }

    case "${action}" in
        install)
            if is_installed; then
                log_success "neovim already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        update)
            if is_installed; then
                do_update
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version)
            if is_installed; then
                get_installed_version
            else
                echo "not installed"
                return 1
            fi
            ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
