#!/bin/bash
#==============================================================================
# Podman Installer
#
# Installs Podman container engine using official Ubuntu repositories.
# For Ubuntu 22.04+, Podman is available in the official repos.
#
# Usage: ./podman.sh [install|update|verify]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Source shared libraries
# shellcheck source=scripts/lib/core.sh
source "${SCRIPT_DIR}/../lib/core.sh"
# shellcheck source=scripts/lib/dryrun.sh
source "${SCRIPT_DIR}/../lib/dryrun.sh"
# shellcheck source=scripts/lib/health.sh
source "${SCRIPT_DIR}/../lib/health.sh"
# shellcheck source=scripts/lib/lock.sh
source "${SCRIPT_DIR}/../lib/lock.sh"

#==============================================================================
# Configuration
#==============================================================================

PACKAGE_NAME="podman"

#==============================================================================
# Functions
#==============================================================================

# Check if Podman is installed
is_installed() {
    command_exists podman
}

# Get installed Podman version
get_installed_version() {
    if is_installed; then
        podman --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

# Load config
load_config() {
    if [[ -f "${PROJECT_ROOT}/config.env" ]]; then
        # shellcheck source=/dev/null
        source "${PROJECT_ROOT}/config.env"
    fi
}

# Install Podman
do_install() {
    log_section "Installing Podman"

    load_config

    # Skip if Podman already installed
    if is_installed; then
        local version
        version=$(get_installed_version)
        log_success "Podman already installed: v${version}"
        return 0
    fi

    # Install Podman from official Ubuntu repos
    log_info "Installing Podman from Ubuntu repositories..."
    apt_or_print update -qq
    apt_or_print install -y -qq podman

    # Install additional useful packages
    log_info "Installing additional container tools..."
    apt_or_print install -y -qq podman-compose podman-docker slirp4netns uidmap

    # Enable and start podman socket for Docker API compatibility
    if [[ "${PODMAN_SOCKET_ENABLED:-true}" == "true" ]]; then
        log_info "Enabling Podman socket for Docker API compatibility..."
        if ! is_dry_run; then
            systemctl --user enable --now podman.socket 2>/dev/null || true
        else
            echo "[DRY-RUN] Would enable podman.socket"
        fi
    fi

    # Update lock file
    local version
    version=$(get_installed_version)
    if [[ -n "${version}" ]]; then
        update_lock "${PACKAGE_NAME}" "${version}"
    fi

    log_success "Podman installed successfully"
}

# Verify installation
verify() {
    log_section "Verifying Podman Installation"

    # Check podman command
    if is_installed; then
        local version
        version=$(get_installed_version)
        health_pass "podman" "v${version}"
    else
        health_fail "podman" "not installed"
        return 1
    fi

    # Check rootless configuration
    if [[ -f /etc/subuid ]] && grep -q "^${USER}:" /etc/subuid 2>/dev/null; then
        health_pass "rootless" "subuid configured"
    else
        health_warn "rootless" "subuid may need configuration"
    fi

    # Check podman-compose
    if command_exists podman-compose; then
        health_pass "podman-compose" "installed"
    else
        health_warn "podman-compose" "not installed"
    fi

    return 0
}

# Create shell config
create_shell_config() {
    local config_dir="${HOME}/.config/shell"
    local config_file="${config_dir}/40-podman.sh"

    mkdir -p "${config_dir}" 2>/dev/null || true

    local content="# Podman configuration
# Generated by podman.sh

# Podman aliases
alias p='podman'
alias pc='podman-compose'
alias pps='podman ps'
alias pimg='podman images'
alias plogs='podman logs -f'
alias pexec='podman exec -it'

# Docker compatibility is provided by podman-docker package
# The 'docker' command automatically uses podman

# Enable Docker API socket path for compatibility
# export DOCKER_HOST=unix://\${XDG_RUNTIME_DIR}/podman/podman.sock
"
    write_or_print "${config_file}" "${content}"
}

#==============================================================================
# Main
#==============================================================================

main() {
    parse_dry_run_flag "$@"

    local action="${1:-install}"

    # Check if enabled
    load_config
    if [[ "${PODMAN_ENABLED:-true}" != "true" ]]; then
        log_info "Podman is disabled in config"
        return 0
    fi

    case "${action}" in
        install)
            do_install
            create_shell_config
            verify
            ;;
        update)
            log_info "Updating Podman via apt..."
            apt_or_print update -qq
            apt_or_print upgrade -y -qq podman podman-compose
            verify
            ;;
        verify)
            verify
            ;;
        version)
            if is_installed; then
                get_installed_version
            else
                echo "not installed"
                return 1
            fi
            ;;
        *)
            echo "Usage: $0 [install|update|verify|version] [--dry-run]"
            exit 1
            ;;
    esac

    if is_dry_run; then
        print_dry_run_summary
    fi
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
