#!/bin/bash
#==============================================================================
# Starship Installer
#
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs
#
# Installs via Homebrew for latest version
#
# Usage: ./starship.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# shellcheck source=scripts/lib/core.sh
source "${SCRIPT_DIR}/../lib/core.sh"
# shellcheck source=scripts/lib/health.sh
source "${SCRIPT_DIR}/../lib/health.sh"
# shellcheck source=scripts/lib/dryrun.sh
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="starship"

# shellcheck source=scripts/lib/brew.sh
source "${SCRIPT_DIR}/../lib/brew.sh"

is_installed() { command_exists starship; }

get_installed_version() {
    if is_installed; then
        starship --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

do_install() {
    log_info "Installing starship via Homebrew..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: brew install starship"
        return 0
    fi

    if ! command_exists brew; then
        log_error "Homebrew not installed. Please install homebrew first."
        return 1
    fi

    brew install starship

    log_success "starship installed"
}

do_update() {
    log_info "Updating starship via Homebrew..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: brew upgrade starship"
        return 0
    fi

    if ! command_exists brew; then
        log_error "Homebrew not installed. Please install homebrew first."
        return 1
    fi

    brew upgrade starship || {
        log_info "starship is already up-to-date"
    }

    log_success "starship updated"
}

verify() {
    if ! is_installed; then
        health_fail "${PACKAGE_NAME}" "not installed"
        return 1
    fi
    health_pass "${PACKAGE_NAME}" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/900-starship.sh"
    mkdir -p "$(dirname "${config_file}")" 2>/dev/null || true
    # shellcheck disable=SC2016
    write_or_print "${config_file}" '# Starship prompt
# Generated by starship.sh

if command -v starship &> /dev/null; then
    eval "$(starship init zsh)"
fi
'
}

main() {
    parse_dry_run_flag "$@"

    # Extract action from args, skipping flags
    local action="install"
    for arg in "$@"; do
        case "${arg}" in
            --dry-run|-n) ;;  # Skip flags
            *) action="${arg}"; break ;;
        esac
    done

    # shellcheck source=config.env.template
    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_STARSHIP_ENABLED:-true}" != "true" ]] && { log_info "starship disabled"; return 0; }

    case "${action}" in
        install)
            if is_installed; then
                log_success "starship already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        update)
            if is_installed; then
                do_update
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version)
            if is_installed; then
                get_installed_version
            else
                echo "not installed"
                return 1
            fi
            ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
