#!/bin/bash
set -e
set -u
set -o pipefail

#==============================================================================
# Shell Configuration Generator
#
# Generates modular shell configuration files in ~/.config/shell/
# and creates ~/.zsh_custom_config that sources them all.
#
# Location: scripts/shared/generate-shell-config.sh
#==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Source shared libraries
# shellcheck source=scripts/lib/core.sh
source "${SCRIPT_DIR}/../lib/core.sh"
# shellcheck source=scripts/lib/dryrun.sh
source "${SCRIPT_DIR}/../lib/dryrun.sh"

#==============================================================================
# Configuration
#==============================================================================

SHELL_CONFIG_DIR="${HOME}/.config/shell"
CUSTOM_CONFIG_FILE="${HOME}/.zsh_custom_config"

#==============================================================================
# Core Shell Config Files
#==============================================================================

# Generate the base environment config
generate_00_env() {
    local file="${SHELL_CONFIG_DIR}/00-env.sh"
    log_info "Generating: 00-env.sh"

    local content
    content=$(cat << 'EOF'
# Base environment configuration
# Generated by generate-shell-config.sh

# Locale
export LANG="${LANG:-en_US.UTF-8}"
export LC_ALL="${LC_ALL:-en_US.UTF-8}"

# Editor
export EDITOR="${EDITOR:-nvim}"
export VISUAL="${VISUAL:-$EDITOR}"

# History
export HISTSIZE=10000
export SAVEHIST=10000

# Less
export LESS="-R"
EOF
)
    write_or_print "${file}" "${content}"
}

# Generate PATH configuration
generate_10_path() {
    local file="${SHELL_CONFIG_DIR}/10-path.sh"
    log_info "Generating: 10-path.sh"

    local content
    content=$(cat << 'EOF'
# PATH configuration
# Generated by generate-shell-config.sh

# Add local bin directories to PATH
[[ -d "${HOME}/.local/bin" ]] && export PATH="${HOME}/.local/bin:${PATH}"
[[ -d "${HOME}/bin" ]] && export PATH="${HOME}/bin:${PATH}"
EOF
)
    write_or_print "${file}" "${content}"
}

# Generate aliases
generate_20_aliases() {
    local file="${SHELL_CONFIG_DIR}/20-aliases.sh"
    log_info "Generating: 20-aliases.sh"

    local content
    content=$(cat << 'EOF'
# Common aliases
# Generated by generate-shell-config.sh

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# List files
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'

# Safety
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Git shortcuts
alias g='git'
alias gs='git status'
alias gd='git diff'
alias gl='git log --oneline -20'
alias gp='git pull'
alias gpu='git push'

# Docker shortcuts
alias d='docker'
alias dc='docker compose'
alias dps='docker ps'
alias dimg='docker images'
EOF
)
    write_or_print "${file}" "${content}"
}

#==============================================================================
# Main Config File Generator
#==============================================================================

# Generate the main ~/.zsh_custom_config that sources all shell configs
generate_custom_config() {
    log_info "Generating: ~/.zsh_custom_config"

    local content
    content=$(cat << 'EOF'
# Custom shell configuration
# Generated by generate-shell-config.sh
# Sources all files in ~/.config/shell/ in order

# Source all shell config files
if [[ -d "${HOME}/.config/shell" ]]; then
    for config_file in "${HOME}/.config/shell"/*.sh; do
        [[ -f "$config_file" ]] && source "$config_file"
    done
fi
EOF
)
    write_or_print "${CUSTOM_CONFIG_FILE}" "${content}"
}

#==============================================================================
# Main Functions
#==============================================================================

generate_all_configs() {
    log_section "Generating Shell Configuration"

    # Create config directory
    mkdir_or_print "${SHELL_CONFIG_DIR}"

    # Generate core configs
    generate_00_env
    generate_10_path
    generate_20_aliases

    # Note: Tool-specific configs (starship, zoxide, fzf, etc.) are generated
    # by their respective package scripts in scripts/packages/

    # Generate main sourcing file
    generate_custom_config

    log_success "Shell configuration generated"
}

list_configs() {
    log_section "Shell Configuration Files"

    if [[ -d "${SHELL_CONFIG_DIR}" ]]; then
        echo "Directory: ${SHELL_CONFIG_DIR}"
        echo ""
        for file in "${SHELL_CONFIG_DIR}"/*.sh; do
            if [[ -f "${file}" ]]; then
                echo "  $(basename "${file}")"
            fi
        done
    else
        log_warning "Shell config directory does not exist"
    fi

    echo ""
    if [[ -f "${CUSTOM_CONFIG_FILE}" ]]; then
        log_success "Main config: ${CUSTOM_CONFIG_FILE}"
    else
        log_warning "Main config not found: ${CUSTOM_CONFIG_FILE}"
    fi
}

#==============================================================================
# Main
#==============================================================================

main() {
    parse_dry_run_flag "$@"

    local action="generate"

    for arg in "$@"; do
        case "${arg}" in
            --list|-l)
                action="list"
                ;;
            --help|-h)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --dry-run, -n    Preview changes without applying"
                echo "  --list, -l       List current configuration files"
                echo "  --help, -h       Show this help"
                exit 0
                ;;
        esac
    done

    case "${action}" in
        generate)
            generate_all_configs
            if is_dry_run; then
                print_dry_run_summary
            fi
            ;;
        list)
            list_configs
            ;;
    esac
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
