package terragrunt

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jaspreet-dot-casa/cloud-init/pkg/deploy"
	"github.com/jaspreet-dot-casa/cloud-init/pkg/generator"
)

// generateCloudInitInDir generates the cloud-init.yaml file in the specified directory.
func (g *Generator) generateCloudInitInDir(opts *deploy.DeployOptions, machineDir string) (string, error) {
	outputPath := filepath.Join(machineDir, "cloud-init.yaml")

	if err := generator.Generate(opts.Config, outputPath); err != nil {
		return "", fmt.Errorf("failed to generate cloud-init.yaml: %w", err)
	}

	return outputPath, nil
}

// writeTerragruntHCL generates the terragrunt.hcl file in the specified directory.
func (g *Generator) writeTerragruntHCL(opts *deploy.DeployOptions, machineDir string) error {
	tgOpts := opts.Terragrunt

	// Build terragrunt.hcl content
	var sb strings.Builder
	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# VM Configuration - Auto-generated by ucli\n")
	sb.WriteString("#\n")
	sb.WriteString("# To apply: terragrunt init && terragrunt apply\n")
	sb.WriteString("# To destroy: terragrunt destroy\n")
	sb.WriteString("# =============================================================================\n\n")

	// Include root configuration (provides versions.tf)
	sb.WriteString("include \"root\" {\n")
	sb.WriteString("  path = find_in_parent_folders()\n")
	sb.WriteString("}\n\n")

	// Reference the libvirt-vm module using relative path
	// From tf/<vm-name>/ to terragrunt/modules/libvirt-vm is ../../terragrunt/modules/libvirt-vm
	sb.WriteString("terraform {\n")
	sb.WriteString("  source = \"../../terragrunt/modules/libvirt-vm\"\n")
	sb.WriteString("}\n\n")

	// Generate provider configuration with the specified libvirt URI
	sb.WriteString("# Provider configuration - customize libvirt_uri if needed\n")
	sb.WriteString("generate \"provider\" {\n")
	sb.WriteString("  path      = \"provider.tf\"\n")
	sb.WriteString("  if_exists = \"overwrite_terragrunt\"\n")
	sb.WriteString("  contents  = <<-EOF\n")
	sb.WriteString(fmt.Sprintf("    provider \"libvirt\" {\n"))
	sb.WriteString(fmt.Sprintf("      uri = %q\n", tgOpts.LibvirtURI))
	sb.WriteString(fmt.Sprintf("    }\n"))
	sb.WriteString("  EOF\n")
	sb.WriteString("}\n\n")

	// Inputs
	sb.WriteString("# VM inputs - customize as needed\n")
	sb.WriteString("inputs = {\n")
	sb.WriteString(fmt.Sprintf("  vm_name           = %q\n", tgOpts.VMName))
	sb.WriteString(fmt.Sprintf("  vcpu_count        = %d\n", tgOpts.CPUs))
	sb.WriteString(fmt.Sprintf("  memory_mb         = %d\n", tgOpts.MemoryMB))
	sb.WriteString(fmt.Sprintf("  disk_size_gb      = %d\n", tgOpts.DiskGB))
	sb.WriteString(fmt.Sprintf("  autostart         = %t\n", tgOpts.Autostart))
	sb.WriteString(fmt.Sprintf("  ubuntu_image_path = %q\n", tgOpts.UbuntuImage))
	sb.WriteString("  cloud_init_file   = \"${get_terragrunt_dir()}/cloud-init.yaml\"\n")
	sb.WriteString(fmt.Sprintf("  storage_pool      = %q\n", tgOpts.StoragePool))
	sb.WriteString(fmt.Sprintf("  network_name      = %q\n", tgOpts.NetworkName))
	sb.WriteString("}\n")

	// Write the file
	hclPath := filepath.Join(machineDir, "terragrunt.hcl")
	if err := os.WriteFile(hclPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write terragrunt.hcl: %w", err)
	}

	return nil
}
