package terraform

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jaspreet-dot-casa/cloud-init/pkg/deploy"
	"github.com/jaspreet-dot-casa/cloud-init/pkg/generator"
)

// generateCloudInit generates the cloud-init.yaml file using embedded template.
func (d *Deployer) generateCloudInit(opts *deploy.DeployOptions) (string, error) {
	outputPath := filepath.Join(opts.ProjectRoot, "cloud-init", "cloud-init.yaml")

	if err := generator.Generate(opts.Config, outputPath); err != nil {
		return "", fmt.Errorf("failed to generate cloud-init.yaml: %w", err)
	}

	return outputPath, nil
}

// writeTFVars generates the terraform.tfvars file.
func (d *Deployer) writeTFVars(opts *deploy.DeployOptions, cloudInitPath string) error {
	tfOpts := opts.Terraform
	workDir := filepath.Join(opts.ProjectRoot, tfOpts.WorkDir)

	// Build tfvars content
	var sb strings.Builder
	sb.WriteString("# Auto-generated by ucli\n")
	sb.WriteString("# Do not edit manually - regenerate with: ucli create\n\n")

	// VM Configuration
	sb.WriteString("# VM Configuration\n")
	sb.WriteString(fmt.Sprintf("vm_name      = %q\n", tfOpts.VMName))
	sb.WriteString(fmt.Sprintf("vcpu_count   = %d\n", tfOpts.CPUs))
	sb.WriteString(fmt.Sprintf("memory_mb    = %d\n", tfOpts.MemoryMB))
	sb.WriteString(fmt.Sprintf("disk_size_gb = %d\n", tfOpts.DiskGB))
	sb.WriteString("\n")

	// Libvirt Configuration
	sb.WriteString("# Libvirt Configuration\n")
	sb.WriteString(fmt.Sprintf("libvirt_uri  = %q\n", tfOpts.LibvirtURI))
	sb.WriteString(fmt.Sprintf("storage_pool = %q\n", tfOpts.StoragePool))
	sb.WriteString(fmt.Sprintf("network_name = %q\n", tfOpts.NetworkName))
	sb.WriteString("\n")

	// Ubuntu Image
	sb.WriteString("# Ubuntu Cloud Image\n")
	sb.WriteString(fmt.Sprintf("ubuntu_image_path = %q\n", tfOpts.UbuntuImage))
	sb.WriteString("\n")

	// Cloud-init file - use relative path from terraform directory
	relCloudInitPath, err := filepath.Rel(workDir, cloudInitPath)
	if err != nil {
		relCloudInitPath = cloudInitPath // Fall back to absolute path
	}
	sb.WriteString("# Cloud-Init Configuration\n")
	sb.WriteString(fmt.Sprintf("cloud_init_file = %q\n", relCloudInitPath))

	// Write the file
	tfvarsPath := filepath.Join(workDir, "terraform.tfvars")
	if err := os.WriteFile(tfvarsPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write terraform.tfvars: %w", err)
	}

	return nil
}
