package config

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Writer handles writing configuration files.
type Writer struct {
	ProjectRoot string
}

// NewWriter creates a new config writer.
func NewWriter(projectRoot string) *Writer {
	return &Writer{ProjectRoot: projectRoot}
}

// WriteConfigEnv writes the config.env file.
func (w *Writer) WriteConfigEnv(cfg *FullConfig) error {
	var buf bytes.Buffer

	buf.WriteString("#!/bin/bash\n")
	buf.WriteString("#==============================================================================\n")
	buf.WriteString("# Ubuntu Server Configuration\n")
	buf.WriteString("#\n")
	buf.WriteString(fmt.Sprintf("# Generated by ucli on %s\n", time.Now().Format(time.RFC3339)))
	buf.WriteString("#==============================================================================\n\n")

	// User Configuration
	buf.WriteString("#==============================================================================\n")
	buf.WriteString("# User Configuration\n")
	buf.WriteString("#==============================================================================\n\n")
	buf.WriteString(fmt.Sprintf("USER_NAME=%q\n", cfg.FullName))
	buf.WriteString(fmt.Sprintf("USER_EMAIL=%q\n", cfg.Email))
	buf.WriteString(fmt.Sprintf("USER_USERNAME=%q\n", cfg.Username))
	buf.WriteString("\n")

	// Git Configuration
	buf.WriteString("#==============================================================================\n")
	buf.WriteString("# Git Configuration\n")
	buf.WriteString("#==============================================================================\n\n")
	buf.WriteString(fmt.Sprintf("GIT_DEFAULT_BRANCH=%q\n", cfg.GitDefaultBranch))
	buf.WriteString(fmt.Sprintf("GIT_PUSH_AUTO_SETUP_REMOTE=%t\n", cfg.GitPushAutoSetupRemote))
	buf.WriteString(fmt.Sprintf("GIT_PULL_REBASE=%t\n", cfg.GitPullRebase))
	buf.WriteString(fmt.Sprintf("GIT_PAGER=%q\n", cfg.GitPager))
	buf.WriteString(fmt.Sprintf("GIT_URL_REWRITE_GITHUB=%t\n", cfg.GitURLRewriteGithub))
	buf.WriteString("\n")

	// Tailscale Configuration
	buf.WriteString("#==============================================================================\n")
	buf.WriteString("# Tailscale Configuration\n")
	buf.WriteString("#==============================================================================\n\n")
	buf.WriteString(fmt.Sprintf("TAILSCALE_SSH_ENABLED=%t\n", cfg.TailscaleSSHEnabled))
	buf.WriteString(fmt.Sprintf("TAILSCALE_EXIT_NODE_ADVERTISE=%t\n", cfg.TailscaleExitNode))
	buf.WriteString(fmt.Sprintf("TAILSCALE_SSH_CHECK_MODE=%t\n", cfg.TailscaleSSHCheckMode))
	buf.WriteString(fmt.Sprintf("TAILSCALE_SSH_CHECK_PERIOD=%q\n", cfg.TailscaleSSHCheckPeriod))
	buf.WriteString("\n")

	// Package Configuration
	buf.WriteString("#==============================================================================\n")
	buf.WriteString("# Package Configuration\n")
	buf.WriteString("#==============================================================================\n\n")

	// Write package enables (only enabled packages are written)
	for _, pkg := range cfg.EnabledPackages {
		envName := strings.ToUpper(strings.ReplaceAll(pkg, "-", "_"))
		buf.WriteString(fmt.Sprintf("PACKAGE_%s_ENABLED=true\n", envName))
		buf.WriteString(fmt.Sprintf("PACKAGE_%s_VERSION=latest\n", envName))
	}
	buf.WriteString("\n")

	// Docker Configuration
	buf.WriteString("#==============================================================================\n")
	buf.WriteString("# Docker Configuration\n")
	buf.WriteString("#==============================================================================\n\n")
	buf.WriteString(fmt.Sprintf("DOCKER_ENABLED=%t\n", cfg.DockerEnabled))
	buf.WriteString(fmt.Sprintf("DOCKER_ADD_TO_GROUP=%t\n", cfg.DockerAddToGroup))
	buf.WriteString(fmt.Sprintf("DOCKER_START_ON_BOOT=%t\n", cfg.DockerStartOnBoot))
	buf.WriteString("\n")

	path := w.ProjectRoot + "/config.env"
	return os.WriteFile(path, buf.Bytes(), 0644)
}

// WriteSecretsEnv writes the secrets.env file.
func (w *Writer) WriteSecretsEnv(cfg *FullConfig) error {
	// Ensure cloud-init directory exists
	cloudInitDir := filepath.Join(w.ProjectRoot, "cloud-init")
	if err := os.MkdirAll(cloudInitDir, 0755); err != nil {
		return fmt.Errorf("failed to create cloud-init directory: %w", err)
	}

	var buf bytes.Buffer

	buf.WriteString("# Cloud-Init Secrets Configuration\n")
	buf.WriteString("#\n")
	buf.WriteString(fmt.Sprintf("# Generated by ucli on %s\n", time.Now().Format(time.RFC3339)))
	buf.WriteString("# This file should NEVER be committed to git.\n")
	buf.WriteString("#\n\n")

	// Required Configuration
	buf.WriteString("# =============================================================================\n")
	buf.WriteString("# Required Configuration\n")
	buf.WriteString("# =============================================================================\n\n")
	buf.WriteString(fmt.Sprintf("USERNAME=%q\n", cfg.Username))
	buf.WriteString(fmt.Sprintf("HOSTNAME=%q\n", cfg.Hostname))
	buf.WriteString(fmt.Sprintf("SSH_PUBLIC_KEY=%q\n", cfg.SSHPublicKey))
	buf.WriteString("\n")

	// User Information
	buf.WriteString("# =============================================================================\n")
	buf.WriteString("# User Information\n")
	buf.WriteString("# =============================================================================\n\n")
	buf.WriteString(fmt.Sprintf("USER_NAME=%q\n", cfg.FullName))
	buf.WriteString(fmt.Sprintf("USER_EMAIL=%q\n", cfg.Email))
	buf.WriteString("\n")

	// Tailscale Authentication
	buf.WriteString("# =============================================================================\n")
	buf.WriteString("# Optional: Tailscale Authentication\n")
	buf.WriteString("# =============================================================================\n\n")
	buf.WriteString(fmt.Sprintf("TAILSCALE_AUTH_KEY=%q\n", cfg.TailscaleAuthKey))
	buf.WriteString("\n")

	// GitHub Authentication
	buf.WriteString("# =============================================================================\n")
	buf.WriteString("# Optional: GitHub Authentication\n")
	buf.WriteString("# =============================================================================\n\n")
	buf.WriteString(fmt.Sprintf("GITHUB_PAT=%q\n", cfg.GithubPAT))
	buf.WriteString(fmt.Sprintf("GITHUB_USER=%q\n", cfg.GithubUser))
	buf.WriteString("\n")

	// Repository Configuration
	buf.WriteString("# =============================================================================\n")
	buf.WriteString("# Optional: Repository Configuration\n")
	buf.WriteString("# =============================================================================\n\n")
	buf.WriteString(fmt.Sprintf("REPO_URL=%q\n", cfg.RepoURL))
	buf.WriteString(fmt.Sprintf("REPO_BRANCH=%q\n", cfg.RepoBranch))
	buf.WriteString("\n")

	path := w.ProjectRoot + "/cloud-init/secrets.env"
	return os.WriteFile(path, buf.Bytes(), 0600) // More restrictive permissions for secrets
}

// WriteAll writes both config.env and secrets.env files.
func (w *Writer) WriteAll(cfg *FullConfig) error {
	if err := w.WriteConfigEnv(cfg); err != nil {
		return fmt.Errorf("failed to write config.env: %w", err)
	}

	if err := w.WriteSecretsEnv(cfg); err != nil {
		return fmt.Errorf("failed to write secrets.env: %w", err)
	}

	return nil
}
