#!/bin/bash
#==============================================================================
# Legacy Package Cleanup Script
#
# One-time cleanup script to remove packages installed via apt, GitHub releases,
# or official installers before switching to Homebrew-based installation.
#
# Run this ONCE before running install-all.sh with Homebrew packages.
#
# Usage: sudo ./cleanup-legacy.sh [--dry-run]
#==============================================================================

set -e
set -u
set -o pipefail

DRY_RUN=false
[[ "${1:-}" == "--dry-run" || "${1:-}" == "-n" ]] && DRY_RUN=true

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }
log_dry() { echo -e "${YELLOW}[DRY-RUN]${NC} Would: $*"; }

run_cmd() {
    if ${DRY_RUN}; then
        log_dry "$*"
    else
        "$@"
    fi
}

#==============================================================================
# Cleanup Functions
#==============================================================================

cleanup_apt_packages() {
    log_info "Cleaning up apt-installed packages..."

    # Packages that were installed via apt and are now via Homebrew
    local apt_packages=(
        "bat"           # Was installed as 'bat' package (binary: batcat)
        "btop"          # Was installed via apt
        "gh"            # Was installed via GitHub CLI apt repo
        "neovim"        # Was installed via apt
        "ripgrep"       # Was installed via apt (binary: rg)
        "fzf"           # Was installed via apt
    )

    for pkg in "${apt_packages[@]}"; do
        if dpkg -l "${pkg}" &>/dev/null; then
            log_info "Removing apt package: ${pkg}"
            run_cmd sudo apt-get remove -y "${pkg}"
        else
            log_success "apt package not installed: ${pkg}"
        fi
    done

    # Remove GitHub CLI apt repository if it exists
    if [[ -f /etc/apt/sources.list.d/github-cli.list ]]; then
        log_info "Removing GitHub CLI apt repository..."
        run_cmd sudo rm -f /etc/apt/sources.list.d/github-cli.list
        run_cmd sudo rm -f /etc/apt/keyrings/githubcli-archive-keyring.gpg
    fi

    # Clean up apt cache
    if ! ${DRY_RUN}; then
        log_info "Running apt autoremove..."
        sudo apt-get autoremove -y
    fi
}

cleanup_usr_local_bin() {
    log_info "Cleaning up /usr/local/bin binaries..."

    # Binaries that were installed from GitHub releases to /usr/local/bin
    local binaries=(
        "delta"
        "lazygit"
        "lazydocker"
        "yq"
        "zellij"
    )

    for bin in "${binaries[@]}"; do
        if [[ -f "/usr/local/bin/${bin}" ]]; then
            log_info "Removing /usr/local/bin/${bin}"
            run_cmd sudo rm -f "/usr/local/bin/${bin}"
        else
            log_success "Binary not found: /usr/local/bin/${bin}"
        fi
    done
}

cleanup_local_bin() {
    log_info "Cleaning up ~/.local/bin binaries..."

    local user_home="${HOME}"

    # Binaries installed by official installers to ~/.local/bin
    local binaries=(
        "starship"
        "zoxide"
        "mise"
        "bat"       # Symlink created for batcat
    )

    for bin in "${binaries[@]}"; do
        if [[ -f "${user_home}/.local/bin/${bin}" || -L "${user_home}/.local/bin/${bin}" ]]; then
            log_info "Removing ~/.local/bin/${bin}"
            run_cmd rm -f "${user_home}/.local/bin/${bin}"
        else
            log_success "Binary not found: ~/.local/bin/${bin}"
        fi
    done
}

cleanup_shell_configs() {
    log_info "Shell configs in ~/.config/shell/ will be regenerated by new installers"
    log_info "No cleanup needed for shell configs"
}

show_homebrew_status() {
    echo ""
    log_info "Checking Homebrew status..."

    if command -v brew &>/dev/null; then
        log_success "Homebrew is installed: $(brew --version | head -1)"
    elif [[ -x "/home/linuxbrew/.linuxbrew/bin/brew" ]]; then
        log_success "Homebrew is installed at /home/linuxbrew/.linuxbrew"
        log_warn "Homebrew is not in PATH. Run: eval \"\$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\""
    else
        log_warn "Homebrew is NOT installed"
        log_info "Install it first, then run install-all.sh"
        log_info "Install command: /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
    fi
}

#==============================================================================
# Main
#==============================================================================

main() {
    echo "========================================"
    echo "  Legacy Package Cleanup Script"
    echo "========================================"
    echo ""

    if ${DRY_RUN}; then
        log_warn "DRY-RUN MODE - No changes will be made"
        echo ""
    fi

    # Check if running as root for apt operations
    if [[ ${EUID} -ne 0 ]] && ! ${DRY_RUN}; then
        log_error "This script needs sudo privileges for apt cleanup"
        log_info "Run with: sudo $0"
        log_info "Or use --dry-run to see what would be cleaned up"
        exit 1
    fi

    cleanup_apt_packages
    echo ""

    cleanup_usr_local_bin
    echo ""

    cleanup_local_bin
    echo ""

    cleanup_shell_configs
    echo ""

    show_homebrew_status
    echo ""

    echo "========================================"
    if ${DRY_RUN}; then
        log_info "Dry run complete. Run without --dry-run to apply changes."
    else
        log_success "Cleanup complete!"
        log_info "You can now run install-all.sh to install packages via Homebrew"
    fi
    echo "========================================"
}

main "$@"
